[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ieee_cis_fraud_detection"
version = "0.0.1"
description = "A short description of the project."
authors = [
  { name = "Alex" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
dependencies = [
    "catboost>=1.2.10",
    "dvc>=3.67.1",
    "fastapi",
    "httpx",
    "ipython",
    "jupyterlab",
    "lightgbm>=4.7.0",
    "loguru",
    "matplotlib",
    "mkdocs",
    "mlflow>=3.15.2",
    "notebook",
    "numpy",
    "pandas",
    "pip",
    "prefect>=3.8.4",
    "pyarrow>=25.0.1",
    "pytest",
    "python-dotenv",
    "ruff",
    "scikit-learn",
    "seaborn>=0.13.2",
    "tqdm",
    "typer",
    "uvicorn",
    "xgboost>=3.4.1",
]
requires-python = "~=3.12.0"


[tool.ruff]
line-length = 99
src = ["ieee_cis_fraud_detection"]
include = ["pyproject.toml", "ieee_cis_fraud_detection/**/*.py"]

[tool.ruff.lint]
extend-select = ["I"]  # Add import sorting

[tool.ruff.lint.isort]
known-first-party = ["ieee_cis_fraud_detection"]
force-sort-within-sections = true

